[pytest]

# Ensure project root is importable
pythonpath = .

# Test discovery
testpaths = tests

# Naming conventions
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Common execution options
addopts =
    -v
    --tb=short

# Markers
markers =
    ui: UI tests
    api: API tests
    e2e: End-to-End tests
    negative: Negative test cases