# utils/mcp_performance_engine.py

import random
import time
from selenium.webdriver.common.by import By


# ==========================================
# MCP - LLM STYLE TEST DATA GENERATOR
# ==========================================
class LLMDataGenerator:
    # Predefined title pool for synthetic note generation (used for variation in test data)
    TITLES = [
        "Meeting Notes",
        "Sprint Planning",
        "Daily Standup",
        "Project Ideas",
        "Automation Notes",
        "Release Checklist",
    ]

    # Predefined description pool for generating realistic note content
    DESCRIPTIONS = [
        "Discussion about roadmap",
        "Automation framework updates",
        "Performance optimization notes",
        "Regression execution summary",
        "Agentic framework validation",
    ]

    # Category labels used for classification-based test scenarios
    CATEGORIES = [
        "Work",
        "Home",
        "Personal",
        "Study",
    ]

    @staticmethod
    def generate_note():
        # Local category pool used for randomized test data generation
        categories = ["Home", "Work", "Personal"]

        # Unix timestamp used to ensure uniqueness of generated test title
        timestamp = int(time.time())

        # Construct and return synthetic note payload for API/UI testing
        return {
            "title": f"AI Note {timestamp}",   # ✅ always unique and valid per execution
            "description": "Generated by MCP AI engine",
            "category": random.choice(categories)
        }


# ==========================================
# MCP - PERFORMANCE MONITOR
# ==========================================
class PerformanceMonitor:

    # SLA threshold for API response validation (in seconds)
    MAX_RESPONSE_TIME = 20

    @staticmethod
    def evaluate_response(response):

        # Extract total API response time from response object
        response_time = response.elapsed.total_seconds()

        # Log measured response time for debugging and reporting
        print(f"\n API Response Time: {response_time:.2f} sec")

        # Performance classification logic based on response latency
        if response_time < 2:
            print("Excellent Performance")

        elif response_time < 5:
            print(" Good Performance")

        elif response_time < 10:
            print(" Acceptable Performance")

        else:
            print(" Slow Performance")

        # Enforce performance SLA; fail test if threshold is exceeded
        assert (
            response_time < PerformanceMonitor.MAX_RESPONSE_TIME
        ), f"API too slow: {response_time:.2f} sec"


# ==========================================
# MCP - FAILURE ANALYZER
# ==========================================
class FailureAnalyzer:

    @staticmethod
    def analyze(error_message):

        # Normalize error message to string for pattern matching
        error_message = str(error_message)

        # Detect Selenium locator-related failure
        if "NoSuchElementException" in error_message:
            return (
                "MCP Analysis: Locator failure detected. "
                "Possible DOM change or incorrect selector."
            )

        # Detect timeout-related failures (application slowness or waits issue)
        elif "TimeoutException" in error_message:
            return (
                "MCP Analysis: Application response delay detected. "
                "Increase intelligent waits."
            )

        # Detect click interception due to overlays/modals
        elif "ElementClickInterceptedException" in error_message:
            return (
                "MCP Analysis: UI overlay blocked click action. "
                "Use JS click fallback."
            )

        # Detect assertion mismatches in validation layer
        elif "AssertionError" in error_message:
            return (
                "MCP Analysis: Validation failed. "
                "Expected and actual results mismatch."
            )

        # Default fallback for unknown/unclassified failures
        return (
            "MCP Analysis: Unknown issue detected. "
            "Manual investigation recommended."
        )


# ==========================================
# MCP - LOCATOR IMPROVEMENT ENGINE
# ==========================================
class LocatorAdvisor:

    @staticmethod
    def suggest(locator):

        # Decompose locator tuple into strategy and value
        by, value = locator

        # Collect improvement suggestions based on locator type
        suggestions = []

        # XPath locators are often brittle in dynamic DOM structures
        if by == By.XPATH:
            suggestions.append(
                "Avoid long dynamic XPath. Prefer stable IDs or CSS selectors."
            )

        # Class-based locators may change frequently in modern UI frameworks
        if by == By.CLASS_NAME:
            suggestions.append(
                "Class names may be dynamic. Prefer data-testid or ID."
            )

        # CSS selectors can become fragile if tightly coupled to UI hierarchy
        if by == By.CSS_SELECTOR:
            suggestions.append(
                "Ensure CSS selectors are not tightly coupled to UI structure."
            )

        # ID locators are generally stable and recommended for automation
        if by == By.ID:
            suggestions.append(
                "Good practice: ID locator is stable and fast."
            )

        # Fallback case when locator strategy does not match known patterns
        if not suggestions:
            suggestions.append(
                "Locator strategy acceptable."
            )

        # Return list of optimization recommendations
        return suggestions