# utils/mcp_performance_engine.py

import random
import time
from selenium.webdriver.common.by import By


# ==========================================
# MCP - LLM STYLE TEST DATA GENERATOR
# ==========================================
class LLMDataGenerator:

    TITLES = [
        "Meeting Notes",
        "Sprint Planning",
        "Daily Standup",
        "Project Ideas",
        "Automation Notes",
        "Release Checklist",
    ]

    DESCRIPTIONS = [
        "Discussion about roadmap",
        "Automation framework updates",
        "Performance optimization notes",
        "Regression execution summary",
        "Agentic framework validation",
    ]

    CATEGORIES = [
        "Work",
        "Home",
        "Personal",
        "Study",
    ]

    @staticmethod
    def generate_note():

        categories = ["Home", "Work", "Personal"]

        timestamp = int(time.time())

        return {
            "title": f"AI Note {timestamp}",   # ✅ always valid
            "description": "Generated by MCP AI engine",
            "category": random.choice(categories)
        }


# ==========================================
# MCP - PERFORMANCE MONITOR
# ==========================================
class PerformanceMonitor:

    MAX_RESPONSE_TIME = 20

    @staticmethod
    def evaluate_response(response):

        response_time = response.elapsed.total_seconds()

        print(f"\n⚡ API Response Time: {response_time:.2f} sec")

        if response_time < 2:
            print("✅ Excellent Performance")

        elif response_time < 5:
            print("✅ Good Performance")

        elif response_time < 10:
            print("⚠️ Acceptable Performance")

        else:
            print("❌ Slow Performance")

        assert (
            response_time < PerformanceMonitor.MAX_RESPONSE_TIME
        ), f"API too slow: {response_time:.2f} sec"


# ==========================================
# MCP - FAILURE ANALYZER
# ==========================================
class FailureAnalyzer:

    @staticmethod
    def analyze(error_message):

        error_message = str(error_message)

        if "NoSuchElementException" in error_message:
            return (
                "MCP Analysis: Locator failure detected. "
                "Possible DOM change or incorrect selector."
            )

        elif "TimeoutException" in error_message:
            return (
                "MCP Analysis: Application response delay detected. "
                "Increase intelligent waits."
            )

        elif "ElementClickInterceptedException" in error_message:
            return (
                "MCP Analysis: UI overlay blocked click action. "
                "Use JS click fallback."
            )

        elif "AssertionError" in error_message:
            return (
                "MCP Analysis: Validation failed. "
                "Expected and actual results mismatch."
            )

        return (
            "MCP Analysis: Unknown issue detected. "
            "Manual investigation recommended."
        )


# ==========================================
# MCP - LOCATOR IMPROVEMENT ENGINE
# ==========================================
class LocatorAdvisor:

    @staticmethod
    def suggest(locator):

        by, value = locator

        suggestions = []

        if by == By.XPATH:
            suggestions.append(
                "Avoid long dynamic XPath. Prefer stable IDs or CSS selectors."
            )

        if by == By.CLASS_NAME:
            suggestions.append(
                "Class names may be dynamic. Prefer data-testid or ID."
            )

        if by == By.CSS_SELECTOR:
            suggestions.append(
                "Ensure CSS selectors are not tightly coupled to UI structure."
            )

        if by == By.ID:
            suggestions.append(
                "Good practice: ID locator is stable and fast."
            )

        if not suggestions:
            suggestions.append(
                "Locator strategy acceptable."
            )

        return suggestions